application: pypalkar23
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries: 
- name: jinja2
  version: latest

handlers:
- url: /blog
  script: blog.application

- url: /
  script: blog.application

- url: /.json
  script: blog.application

- url: /blog/.*
  script: blog.application

- url: /stylesheets
  static_dir: stylesheets

- url: /images
  static_dir: images


